Add volk_8{u,i}_convert_{32,64}f
gnuradio/volk pull request #209
Opened 2018-10-09 15:38 UTC by xloem

based on volk_8u_s32f_convert_32f

Adds 4 kernels to do basic conversion from 8-bit data to floating point.

2019-03-07 21:49 UTC, noc0lour requested changes
Some minor things, but the code looks fine. 
If you don't have a copyright assignment yet please contact bhilburn at gnuradio.org to get one for this and future contributions.

2019-03-07 21:49 UTC, noc0lour commented on kernels/volk/volk_8i_convert_32f.h
> + * Copyright 2012, 2014 Free Software Foundation, Inc.
just 2019 in this case

2019-03-07 21:49 UTC, noc0lour commented on kernels/volk/volk_8i_convert_32f.h
> + * <FIXME>
Probably provide a small example how to use the kernel.

2020-02-23 17:03 UTC, jdemel commented
It seems like this PR is still mergeable. I'd like to merge it but it seems like we are still waiting for a CLA. Is there any progress in that direction?

2020-11-28 11:49 UTC, jdemel commented
@xloem  Is there any update on the CLA?
We start to see merge conflicts and I'd be more than happy to avoid them by merging your PRs.
If you could do a rebase on current master, that would be great too. It'd trigger more CI as well.

2021-02-21 11:47 UTC, jdemel commented
@xloem  I assume there's still no update on your CLA?

Anyways, we adopted a new system: DCO. Thus, you only need to sign off your commits. `git commit -s` for new commits. The details are explained in `DCO.txt`. With `git commit -s` you add a `Signed off by ...` line to the end of your commit message. You can add

I got this approach to sign previous commits from [stackoverflow](https://stackoverflow.com/a/58599218)
```
git rebase --exec 'git commit --amend --no-edit -n -s' -i HEAD~1
```
I updated the option `-s` to lower case. Also, `HEAD~1` should refer to your one commit. It would be great if you could rebase your PR onto current master. If you fix the 2 comments @noc0lour had that would be great too. With DCO you can just put your name in the copyright line.

2021-02-21 12:54 UTC, xloem commented
Hey, I am so sorry, I was working on this years ago during a traumatic flashback to handle paranoia.  I didn't know I had left it open.  I added this so rtl-sdr devices would work more smoothly.

I'm still pretty surprised that gnuradio is using these kind of older approaches to speeding data up.  Everybody is using gpus nowadays.  Is there a reference to work towards adding GPU integration anywhere?

2021-02-21 13:06 UTC, jdemel commented
@xloem no need for a CLA anymore. We decided to go with a DCO approach now. Just like GNU Radio. Just sign off you commit and we can merge it (given positive reviews).

VOLK does still focus on CPU optimization. There's a middle ground between plain CPU implementations and GPU offload. Some situation where optimized CPU support is desirable are latency constraint situations where transferring data back and forth from a GPUs takes too much time. Your kernels are a good example for that actually. You might want to convert your data before processing on a CPU. It would be too costly to transfer them back and forth from a GPU.

2021-02-21 13:26 UTC, xloem commented
re: cpu/gpu.  the latency concern depends on how costly the processing is of course.  it would make sense to share a vector acceleration library with many other projects, so that work and maintenance can be shared.  the biggest ones nowadays might be the machine learning ones, don't really know.

when i originally saw volk, i was excited to have a place to make for very very fast vector operations, but i was sad it didn't use c++, which i usually use the template features of for such things, constructing the code at compile-time for its specific use.  macros might reduce the code duplication in this library and provide for similar optimization.

I've found the DCO document and am working on handling it.

2021-02-21 14:09 UTC, xloem commented
I'm working on this.  It is really hard for me.

I don't actually remember doing the work, but my body sure did.  I have volk checked out on this system, which is from the area I was living when I did the work.  I do not have a branch on this disk that reflects this pull request.  I am having severe amnesia about what is goin as I try to pursue this, making it hard to remember that I am still pursuing it.

I worked very hard for many years to contribute to rtl-sdr work.  I submitted multiple patches to the people who make the open source driver for rtl-sdr.  None of those patches have been accepted; they are still sitting on the mailing list.  They have since gotten a new maintainer, and I was told I must resubmit my patches for them to be reviewed, that they aren't reviewing the old patches.  It is very frightening and exhausting to continue this work.

2021-02-21 15:34 UTC, xloem commented
Okay, so here's what's up:

As technology advances we need open source radios, to stop implant hacking once it becomes a big dangerous thing.  The rtl-sdr is the cheapest radio out there, it should function smoothly and easily, so it can be powerful.

I don't have the capacity to address all the issues mentioned here.  I'm sorry.  It is too hard for me to work on radios right now, and this feature is too low-impact.  I'm working on open source device drivers for eeg equipment, right now.

Thank you so much for staying on this issue for so long, keeping it open for all these years, and being tolerant of my strange behavior.  If I address the things you mention, I'll reopen the PR or a new one.

Be well, and thank you again for your angel-like radio work.

2021-02-21 15:34 UTC, closed without merging

2021-02-21 15:43 UTC, xloem commented
The "reopen" button isn't working for me, but I have signed off that commit.
I copy-pasted the recommended command, the "exec" portion.  I'm trying to do further work but `-s` is actually `--strategy`.  I don't know why it would add a signed-off-by line.

2021-02-21 15:44 UTC, xloem commented
The signed-off commit is 87538b68991b01cb7b4d32af172c5666c4bf92a7

2021-02-21 15:45 UTC, xloem commented
THIS IS REALLY HARD.  WHAT IS GOING ON?

2021-02-22 09:19 UTC, jdemel commented
It seems like this is disabled by github in your specific case:
https://github.com/isaacs/github/issues/361
We can't reopen a PR after a force push.

Could you just open a new PR?

2021-02-23 08:41 UTC, xloem commented
Thanks for pinging me.