Adds Neonv8 support to 32fc_deinterleave_64f_x2 and 32fc_deinterleave_real_64f
gnuradio/volk pull request #283
Opened 2019-09-15 15:46 UTC by dmiralles2009

Adds Neonv8 support to `32fc_deinterleave_64f_x2` and `32fc_deinterleave_real_64f`. The execution speed improvements are shown below

'''
RUN_VOLK_TESTS: volk_32fc_deinterleave_real_64f(131071,1987)
generic completed in 715.809 ms
neon completed in 682.527 ms
Best aligned arch: neon
Best unaligned arch: neon

RUN_VOLK_TESTS: volk_32fc_deinterleave_64f_x2(131071,1987)
generic completed in 1410.47 ms
a_generic completed in 1299.5 ms
neon completed in 1257.89 ms
Best aligned arch: neon
Best unaligned arch: neon
'''

2019-10-30 11:16 UTC, jdemel reviewed
I guess you ran clang format on that file. This makes a review more difficult. Though, in general I agree we should apply strict formatting rules.

I left some comments. In general this PR looks good to me.

2019-10-30 11:16 UTC, jdemel commented on cmake/Toolchains/arm_cortex_a72_hardfp_native.cmake
> +set(CMAKE_CXX_FLAGS "-ffast-math -march=armv8-a -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard" CACHE STRING "" FORCE)
See #282 for that.

2019-10-30 11:16 UTC, jdemel commented on kernels/volk/volk_32f_64f_add_64f.h
> +    __VOLK_PREFETCH(bPtr + 2);
You could also update those pointers her instead of in line 126/7.

2019-11-01 00:34 UTC, michaelld commented
Any further updates to this PR, or do y'all think it is ready for review?

2019-11-07 02:21 UTC, michaelld requested changes
Please leave out the fast math flag for this specific PR. Otherwise, looks OK to me.

2019-11-07 04:02 UTC, dmiralles2009 commented on cmake/Toolchains/arm_cortex_a72_hardfp_native.cmake
> +set(CMAKE_CXX_FLAGS "-ffast-math -march=armv8-a -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard" CACHE STRING "" FORCE)
Adjusted based on the PR discussion

2019-11-07 09:02 UTC, jdemel approved these changes
LGTM

2019-11-07 14:20 UTC, michaelld approved these changes
LGTM

2019-11-07 14:20 UTC, michaelld commented
all CI checks pass; positive reviews -> merging

2019-11-07 14:20 UTC, merged

2021-10-28 08:34 UTC, jdemel commented
@dmiralles2009 Hi. I don't know if you received emails about re-licensing VOLK under LGPL, so I write you here. I'd kindly like to ask you to support us with our re-licensing effort. The details are discussed in #492 .