fix for spurious heap buffer overflow
gnuradio/volk pull request #288
Opened 2019-09-22 12:30 UTC by hcab14

in the last iteration of the loop an element outside the allocated region is loaded which is then never being used -> use `__VOLK_PREFETCH`

performance is about the same as before

https://github.com/gnuradio/volk/issues/229

2019-09-25 19:31 UTC, michaelld requested changes
I see the issue & agree that what you propose is a good solution. Thx!

Requests:

(1) Please move the comment "// start loading next chunk." along with the other lines; means adding it back in where you've already moved the other lines of code.

(2) Please put an empty line after the `__VOLK_PREFETCH` line inside the loops, which follows the current code's pattern of blankspace.

(3)The implementations for `volk_8u_x2_encodeframepolar_8u_a_avx2` in this same file contains the same error. Please fix it too (same same fix) & then we can finalize testing & get this committed!

2019-09-30 08:30 UTC, hcab14 commented
Thank you for your review

> (1) Please move the comment "// start loading next chunk." along with the other lines; means adding it back in where you've already moved the other lines of code.
> (2) Please put an empty line after the `__VOLK_PREFETCH` line inside the loops, which follows the current code's pattern of blankspace.

Please have a look and see if it is now ok

> (3)The implementations for `volk_8u_x2_encodeframepolar_8u_a_avx2` in this same file contains the same error. Please fix it too (same same fix) & then we can finalize testing & get this committed!

While looking at the code I realized that the SSE3 code can be shortened using the same technique: it contained an explicit last iteration at the end which now is inside the for loop.

2019-10-25 00:14 UTC, michaelld approved these changes
LGTM & CI passes. The failure is for a different kernel/s.

2019-10-25 00:15 UTC, michaelld commented
I like the way you rolled the final iteration back into the main loop, which as you note shortens the code very nicely!

2019-10-25 00:16 UTC, michaelld commented
@jdemel Do you wish to review here?

2019-10-25 08:10 UTC, jdemel commented
I like this PR too. After the changes @michaelld requested the code looks fine.

2019-10-25 09:02 UTC, hcab14 commented
> I like this PR too. After the changes @michaelld requested the code looks fine.

Let me know if further changes are required or if I missed to implement any of the requested changes.

2019-10-27 12:10 UTC, michaelld approved these changes
LGTM; thanks!

2019-10-27 12:10 UTC, merged