Update README.md
gnuradio/volk pull request #429
Opened 2020-12-22 17:54 UTC by JamMarHer

Advanced SIMD (aka NEON) is mandatory for AArch64.
There is no need for adding extra options to the compiler for 64 bit.

2021-01-02 14:47 UTC, jdemel reviewed
Thanks for your contribution!

Do you mind to add your 64bit comment in the README as well? This might be helpful for new users.

2021-02-14 18:24 UTC, michaelld requested changes
The README file needs some work ; I see a typo (likely more than 1) and some errors with respect to macOS. We need a section for how to handle Apple ARM64 / Aarch64. This change is fine, but I agree with @jdemel that I'd like to see your comment herein noted in the README file itself. @JamMarHer can you make this change? If not I'll look into a new PR that does this & more. Thx!

2021-02-21 11:30 UTC, jdemel approved these changes
LGTM.

Thanks for your contribution!

2021-02-21 11:33 UTC, jdemel commented
@michaelld do we need these commits to be signed off?

2021-03-08 17:29 UTC, michaelld commented
> @michaelld do we need these commits to be signed off?

I think these are good to go as-is. They are small and not to any code. Not sure if that's what you were going for.

2021-03-08 17:30 UTC, michaelld approved these changes
LGTM; thx!

2021-03-08 17:30 UTC, michaelld commented
I'm going to go ahead and merge based on my prior comment.

2021-03-08 17:30 UTC, merged