Fix python version detection
gnuradio/volk pull request #451
Opened 2021-02-15 22:03 UTC by yarda

Fixes #450

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

2021-02-15 22:07 UTC, yarda commented
I guess the '>' is OK, because there are usually more data in the tuple (like e.g. 'stable'), so the '>' should much anything newer than '3.4', e.g. '3.4.0' stable version including.

2021-02-15 23:51 UTC, michaelld requested changes
Very minor nitpick change. After that, I agree that we do need this change exactly for the reason in the issue noted! I did some playing around in Python and verified that this method works while the current method won't with Python 3.10 or even 3.9.10 ... basically any double-digit version portion.

2021-02-15 23:51 UTC, michaelld commented on CMakeLists.txt
> +VOLK_PYTHON_CHECK_MODULE("python >= 3.4" sys "sys.version_info > (3, 4)" PYTHON_MIN_VER_FOUND)
To be fair, should be ">=" since in theory we could use Python 3.4.0 & this change would prevent that version from being accepted.

2021-02-16 00:16 UTC, michaelld approved these changes
LGTM; thx!

2021-02-20 11:28 UTC, merged