Use CpuFeatures target
gnuradio/volk pull request #603
Opened 2022-09-27 20:18 UTC by jsallay

The build process is more flexible if we use cmake targets rather than directly linking to libraries. The target is used in other places in the CMakeLists.txt, but was not used in the target_link_libraries command.

2022-09-28 14:06 UTC, marcusmueller commented
"Build static on ubuntu-latest" fails because:
```
  Target "volk_static" links to:
    CpuFeatures::cpu_features
  but the target was not found. 
```

don't know why that happens, but not on the older ubuntus.

2022-09-28 14:42 UTC, jsallay commented
I don't understand either. When I get a break, I was going to try to
recreate the error in a docker container.

On Wed, Sep 28, 2022, 10:07 AM Marcus Müller ***@***.***>
wrote:

> "Build static on ubuntu-latest" fails because:
>
>   Target "volk_static" links to:
>     CpuFeatures::cpu_features
>   but the target was not found.
>
> don't know why that happens, but not on the older ubuntus.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gnuradio/volk/pull/603#issuecomment-1260970235>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPWDXF4ORHHJF7KKVYGAGDWARGI5ANCNFSM6AAAAAAQXEB3OE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-28 15:49 UTC, marcusmueller commented
hm maybe the others use a directly downloaded cpufeatures and the most current one relies on a ubuntu package?

2022-09-29 02:01 UTC, jdemel submitted a review, later dismissed
LGTM. I was under the impression we would do this everywhere. Also, I assumed `cpu_features` is an alias for `CpuFeatures::cpu_features`. Do we use the same approach for the dynamic library?

2022-09-29 16:03 UTC, michaelld requested changes
LGTM after this change

2022-09-29 16:03 UTC, michaelld commented on lib/CMakeLists.txt
> +    target_link_libraries(volk_static PRIVATE CpuFeatures::cpu_features)
To be consistent, please do the same for line 537 `target_link_libraries(volk PRIVATE cpu_features)`

2023-09-13 06:49 UTC, ashley-b commented
Any chance of this getting merged in ?

2023-09-13 08:45 UTC, jdemel commented
@jsallay I guess @ashley-b 's question is mostly direct at you.

I'd like to merge this as soon as all issues are fixed. That would be 
1. the DCO issue which should be trivial to fix
2. the `ubuntu-latest` issue. Unfortunately, the error message is gone by now. It should be simple to trigger our CI though with a simple push with the DCO fix.

2023-09-13 09:24 UTC, ashley-b commented
@jsallay Thanks for the quick follow up, I just tried building it in a ubuntu container and it built with out error

lsb_release -a
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

Also I noticed not all the target_link_librarys for cpu_feature have been changed to use modern CMake targets.

https://github.com/jsallay/volk/blob/823e88aec459011ebd519f50ec2caa2ccc9bcb3b/lib/CMakeLists.txt#L537

and

This block does not make sense, since both lines of the if/else seem to do the same thing
https://github.com/jsallay/volk/blob/823e88aec459011ebd519f50ec2caa2ccc9bcb3b/lib/CMakeLists.txt#L510C1-L517C6

2023-09-13 12:25 UTC, jsallay commented on lib/CMakeLists.txt
> +    target_link_libraries(volk_static PRIVATE CpuFeatures::cpu_features)
Done

2023-09-13 12:26 UTC, jsallay commented
Looks like `CpuFeature::cpu_features` is the consistently defined target.

2023-09-13 13:12 UTC, jdemel commented
@jsallay thanks for taking care of this PR. It looks good to me now. All the comments are addressed. Merging.

2023-09-13 13:12 UTC, merged