New kernels for arctan
gnuradio/volk pull request #633
Opened 2023-09-21 15:56 UTC by Ka-zam

New arctan kernels with improved accuracy and 2.5x speedup.

Prior:
```
RUN_VOLK_TESTS: volk_32f_atan_32f(131071,1987)
a_avx2_fma completed in 184.81 ms
a_avx completed in 200.609 ms
a_sse4_1 completed in 364.564 ms
u_avx2_fma completed in 182.698 ms
u_avx completed in 182.903 ms
u_sse4_1 completed in 370.45 ms
generic completed in 2222.25 ms
Best aligned arch: u_avx2_fma
Best unaligned arch: u_avx2_fma
```
With this PR:
```
RUN_VOLK_TESTS: volk_32f_atan_32f(131071,1987)
a_avx2_fma completed in 76.8184 ms
a_avx2 completed in 77.7383 ms
a_sse4_1 completed in 153.017 ms
u_avx2_fma completed in 78.2237 ms
u_avx2 completed in 78.3921 ms
u_sse4_1 completed in 152.178 ms
generic completed in 2218.09 ms
Best aligned arch: a_avx2_fma
Best unaligned arch: u_avx2_fma
```

2023-09-25 07:53 UTC, jdemel commented
Thanks for your contribution. One quick fix, the DCO check failed. Luckily it contains a tailored description on how to fix it in your case.

The other CI failures are unrelated. Let's see if they go through on the second try. Finally, the code looks good.

2023-09-26 08:00 UTC, jdemel requested changes
Thanks for your PR! I added a few comments.

2023-09-26 08:00 UTC, jdemel commented on cpu_features
Could you revert this submodule update? This just got updated in #631 along with some more necessary fixes. It'll be quite a mess to merge this.
I suggest to rebase this PR on top of #631 to make it easier.

2023-09-26 08:00 UTC, jdemel commented on include/volk/volk_avx2_intrinsics.h
> + * Copyright 2015, 2023 Free Software Foundation, Inc.
Since we changed to DCO, you can just add a line with your name:
```
 * Copyright 2023 Kazam
```
You can choose your github handle or your real name.

2023-09-26 08:00 UTC, jdemel commented on include/volk/volk_avx2_intrinsics.h
> +    arctan = _mm256_fmadd_ps(x_times_x, arctan, a1);
Aren't these part of the avx2 fma extension? In this case, I suggest to habe this function in a file with a corresponding name.

2023-09-26 08:00 UTC, jdemel commented on include/volk/volk_avx_intrinsics.h
> + * Copyright 2015, 20233 Free Software Foundation, Inc.
A little typo and the same comment as before applies.

2023-09-26 08:00 UTC, jdemel commented on include/volk/volk_sse_intrinsics.h
> + * Copyright 2015, 2023 Free Software Foundation, Inc.
see previous comment.

2023-09-26 08:00 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> + * Copyright 2014, 2023 Free Software Foundation, Inc.
see previous comment.

2023-09-26 08:00 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_a_avx2_fma(float* out, const float* in, uint32_t num_points)
I suggest to stick to `unsigned int num_points` here. Otherwise, we would probably run into issues with backwards compatibility.

2023-09-26 08:00 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_a_avx2(float* out, const float* in, uint32_t num_points)
see previous comment.

2023-09-26 08:00 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_a_sse4_1(float* out, const float* in, uint32_t num_points)
see previous comment.

2023-09-26 08:00 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_u_avx2_fma(float* out, const float* in, uint32_t num_points)
see previous comment.

2023-09-26 08:00 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_polynomial(float* out, const float* in, uint32_t num_points)
Does that overwrite the `_generic` kernel? The generic kernel should stay as a fall back and reference.
I suggest to add the `_polynomial` version as another alternative.

2023-09-26 08:02 UTC, jdemel commented on cpu_features
Could you use #631 as a base for your PR? Otherwise it'll probably be very complicated to merge this PR. Also, #631 should include all the improvements you'd need. Or is anything missing there?

2023-09-26 11:03 UTC, Ka-zam commented on include/volk/volk_avx2_intrinsics.h
> +    arctan = _mm256_fmadd_ps(x_times_x, arctan, a1);
Agree

2023-09-26 18:19 UTC, Ka-zam commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_polynomial(float* out, const float* in, uint32_t num_points)
No, it doesn't overwrite it. It's a way to make sure relative accuracy is maintained. The _polynomial function is the scalar version of the vectorized function calls. Still 9 times faster than std::atan.
```
$ volk_profile -R atan_3

RUN_VOLK_TESTS: volk_32f_atan_32f(131071,1987)
a_avx2_fma completed in 129.439 ms
a_avx2 completed in 121.158 ms
a_sse4_1 completed in 229.77 ms
u_avx2_fma completed in 120.851 ms
u_avx2 completed in 121.311 ms
u_sse4_1 completed in 234.745 ms
polynomial completed in 354.254 ms      <---------------------
generic completed in 2987.92 ms         <---------------------
Best aligned arch: u_avx2_fma
Best unaligned arch: u_avx2_fma

```

2023-09-26 18:32 UTC, Ka-zam commented on cpu_features
I'm not sure how to do this. I tried but now all I get is errors like this:
```
git pull
warning: skipped previously applied commit 651ef82
warning: skipped previously applied commit 9fe77b0
warning: skipped previously applied commit b47f109
warning: skipped previously applied commit 8f5da46
warning: skipped previously applied commit 2fb6ba4
warning: skipped previously applied commit 892e707
warning: skipped previously applied commit 63638f0
warning: skipped previously applied commit c8abd03
warning: skipped previously applied commit e476a32
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Auto-merging CMakeLists.txt
Failed to merge submodule cpu_features (commits don't follow merge-base)
CONFLICT (submodule): Merge conflict in cpu_features
Recursive merging with submodules currently only supports trivial cases.
Please manually handle the merging of each conflicted submodule.
This can be accomplished with the following steps:
 - go to submodule (cpu_features), and either merge commit ba4bffa
   or update to an existing commit which has merged those changes
 - come back to superproject and run:

      git add cpu_features

   to record the above merge or update
 - resolve any other conflicts in the superproject
 - commit the resulting index in the superproject
error: could not apply c3bad58... cpu_features: Update submodule pointer and new CMake target name
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply c3bad58... cpu_features: Update submodule pointer and new CMake target name
```

2023-09-27 10:21 UTC, jdemel commented on kernels/volk/volk_32f_atan_32f.h
> +volk_32f_atan_32f_polynomial(float* out, const float* in, uint32_t num_points)
Ah! the git diff is confusing. The file still contains `_generic` kernel.

2023-09-27 10:24 UTC, jdemel commented on cpu_features
Did you update `cpu_features` in a separate commit? In that case you can cherry-pick the other commits and just get rid of the updated submodule pointer.

2023-09-27 10:26 UTC, jdemel commented on cpu_features
It seems like the submodule pointer update was part of commit `bc074d7e6a2bffd0b3e80558f5d618a84427cd99`.

2023-09-27 11:13 UTC, Ka-zam commented on cpu_features
I think it should work now? I didn't update cpu_features, I think it got merged by mistake.

2023-09-28 06:39 UTC, Ka-zam commented
I really think we're done now! Realized I wanted to rename some functions and also remove unused polynomials.

2023-10-02 08:31 UTC, Ka-zam commented
@jdemel Can we merge? I have a few more PRs that depend on this.

2023-10-03 07:44 UTC, jdemel approved these changes
LGTM.

I was worried about the cpu_features changes but they are part of the PRs that are already merged. Thanks for rebasing your work on it.

2023-10-03 07:45 UTC, merged