Add length checks to conv_k7 kernels
gnuradio/volk pull request #644
Opened 2023-10-13 13:33 UTC by argilo

The `volk_8u_conv_k7_r2puppet_8u` kernels require an input vector length of at least 12 = (k-1)*r; if the input is shorter than 12 then `framebits / 2 - excess` (an unsigned int) underflows and turns into a huge number, which causes a buffer overflow in `chainback_viterbi`. I think it makes sense to add a length check so that out-of-bounds memory access does not occur if the user passes in a vector that is too short.

2023-10-13 13:36 UTC, argilo commented
Valgrind report:
```
RUN_VOLK_TESTS: volk_8u_conv_k7_r2puppet_8u(11,1)
==646095== Invalid read of size 4
==646095==    at 0x4B4CE69: chainback_viterbi (volk_8u_conv_k7_r2puppet_8u.h:63)
==646095==    by 0x4B4D2A3: volk_8u_conv_k7_r2puppet_8u_spiral (volk_8u_conv_k7_r2puppet_8u.h:170)
==646095==    by 0x48DFBF3: volk_8u_conv_k7_r2puppet_8u_manual (volk.c:11523)
==646095==    by 0x12AD39: run_cast_test2(void (*)(void*, void*, unsigned int, char const*), std::vector<void*, std::allocator<void*> >&, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (qa_utils.cc:269)
==646095==    by 0x12850D: run_volk_tests(volk_func_desc, void (*)(), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, std::complex<float>, unsigned int, unsigned int, std::vector<volk_test_results_t, std::allocator<volk_test_results_t> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool) (qa_utils.cc:649)
==646095==    by 0x127809: run_volk_tests(volk_func_desc, void (*)(), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, volk_test_params_t, std::vector<volk_test_results_t, std::allocator<volk_test_results_t> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (qa_utils.cc:507)
==646095==    by 0x11E0DD: main (volk_profile.cc:139)
==646095==  Address 0x10540bb60 is not stack'd, malloc'd or (recently) free'd
==646095== 
==646095== 
==646095== Process terminating with default action of signal 11 (SIGSEGV)
==646095==  Access not within mapped region at address 0x10540BB60
==646095==    at 0x4B4CE69: chainback_viterbi (volk_8u_conv_k7_r2puppet_8u.h:63)
==646095==    by 0x4B4D2A3: volk_8u_conv_k7_r2puppet_8u_spiral (volk_8u_conv_k7_r2puppet_8u.h:170)
==646095==    by 0x48DFBF3: volk_8u_conv_k7_r2puppet_8u_manual (volk.c:11523)
==646095==    by 0x12AD39: run_cast_test2(void (*)(void*, void*, unsigned int, char const*), std::vector<void*, std::allocator<void*> >&, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (qa_utils.cc:269)
==646095==    by 0x12850D: run_volk_tests(volk_func_desc, void (*)(), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, std::complex<float>, unsigned int, unsigned int, std::vector<volk_test_results_t, std::allocator<volk_test_results_t> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool) (qa_utils.cc:649)
==646095==    by 0x127809: run_volk_tests(volk_func_desc, void (*)(), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, volk_test_params_t, std::vector<volk_test_results_t, std::allocator<volk_test_results_t> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (qa_utils.cc:507)
==646095==    by 0x11E0DD: main (volk_profile.cc:139)
==646095==  If you believe this happened as a result of a stack
==646095==  overflow in your program's main thread (unlikely but
==646095==  possible), you can try to increase the size of the
==646095==  main thread stack using the --main-stacksize= flag.
==646095==  The main thread stack size used in this run was 8388608.
```

2023-10-14 08:39 UTC, jdemel requested changes
The approach looks good to me.

Could you add `{ ... }` around the return statement though. I know this is valid code but it is prone to errors.

2023-10-14 14:13 UTC, argilo commented
Sure. Done.

2023-10-22 11:56 UTC, jdemel approved these changes
LGTM

2023-10-22 11:56 UTC, merged